### ISSUE TITLE
Add form validations to dashboard

### ISSUE THREAD

**Issue by m-ke** [m-ke/cre-dashboard#23]
Add validation to all forms we have on the dashboard

**b-input**
1) set `name` in input to field name (you can come up with your own)
2) set `v-validate` to all validations you want, separate with `|`. Note the double quotes( " ' xxxx ' ")

**b-field**
1) set `type`, adjust field name according to what's set as `name` in input
2) set `message`, again adjust the field name 

```
        <b-field
          :type="errors.has('email') ? 'is-danger' : ''"
          :message="errors.has('email') ? errors.first('email') : ''"
        >
          <b-input
            v-validate="'required|email'"
            v-model="email"
            type="text"
            name="email"
            placeholder="email address"
            icon="account"
          />
        </b-field>
```

List of possible validation rules:
https://baianat.github.io/vee-validate/guide/rules.html

**Comment by Sjefkesuit** [comment]
@m-ke added a lot of the validations in places where I was able to do it without the risk of messing things up (basically don't know how to make it work where we don't use b-field and b-input). I also did not do it for the billing section as I don't think we actually need that section now that we use Pabbly and they should provide their billing info directly there (maybe I am missing something and if we need it let me know so I can add the validations there as well).

I did mess something up with the branches, hopefully nothing serious (I think I merged the branches the wrong way around)

**Comment by Sjefkesuit** [comment]
@Sjefkesuit for V numeric fields use: https://www.npmjs.com/package/vue-numeric
